version: '2'
services:

  # The Application php
  app:
    env_file: .env
    build:
      context: .
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    container_name: paulownia_app
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    entrypoint: ./docker/entrypoint.sh
    depends_on:
      - database
  # The Web Server
  web:
    image: nginx:stable-alpine
    container_name: paulownia_web
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    ports:
      - 86:80
    depends_on:
      - app
  node:
    image: node:10
    stdin_open: true
    working_dir: /var/www
    volumes_from:
      - app
    tty: true
    command: npm run watch
    volumes:
      - .:/var/www
  # The Database
  database:
    container_name: paulownia_database
    image: mariadb:10
    env_file: .env
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
    ports:
      - 3308:3306