@extends('layouts.public')
@section('content')
    @include('public/main/slider')
    @include('public/main/promotions')
    @include('public/main/why_we')
    @include('public/main/bestsellers')
    @include('public/main/deal_of_day')
    @include('public/main/featured')
    @include('public/main/feedbacks')
    @include('public/main/news', ['news' => $news])
    @include('public/main/partners')
    @include('public/blocks/subscribe')
@endsection
